import type { Product } from '@/types';

export const PRODUCTS_CATALOG: Product[] = [
  {
    "id": "prod_001",
    "name": "Black Embroidered Kurti",
    "description": "Premium cotton black kurti with intricate thread embroidery on neckline.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 87,
    "stock": 12,
    "sku": "FA-001",
    "tags": [
      "kurti",
      "ethnic",
      "black",
      "embroidery"
    ],
    "featured": true
  },
  {
    "id": "prod_002",
    "name": "Pure Chanderi Silk Saree",
    "description": "Handwoven pure Chanderi silk saree with zari border and matching blouse piece.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 134,
    "stock": 8,
    "sku": "FA-002",
    "tags": [
      "saree",
      "silk",
      "chanderi",
      "festive"
    ],
    "featured": true
  },
  {
    "id": "prod_003",
    "name": "Oversized Cotton Graphic Tee",
    "description": "240 GSM heavyweight combed cotton oversized t-shirt with aesthetic typography.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 181,
    "stock": 25,
    "sku": "FA-003",
    "tags": [
      "tshirt",
      "oversized",
      "streetwear",
      "cotton"
    ],
    "featured": false
  },
  {
    "id": "prod_004",
    "name": "Classic Indigo Denim Jacket",
    "description": "Timeless vintage wash denim jacket with brass button closures and dual chest pockets.",
    "price": 1899,
    "originalPrice": 2999,
    "discount": 37,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 228,
    "stock": 14,
    "sku": "FA-004",
    "tags": [
      "denim",
      "jacket",
      "outerwear",
      "indigo"
    ],
    "featured": true
  },
  {
    "id": "prod_005",
    "name": "Slim Fit Linen Casual Shirt",
    "description": "Breathable 100% French linen button-down shirt designed for effortless summer styling.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 275,
    "stock": 19,
    "sku": "FA-005",
    "tags": [
      "shirt",
      "linen",
      "casual",
      "summer"
    ],
    "featured": false
  },
  {
    "id": "prod_006",
    "name": "Floral Print Anarkali Gown",
    "description": "Flared floor-length georgette Anarkali dress featuring digital botanical prints.",
    "price": 1299,
    "originalPrice": 2199,
    "discount": 41,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 322,
    "stock": 6,
    "sku": "FA-006",
    "tags": [
      "anarkali",
      "gown",
      "ethnic",
      "floral"
    ],
    "featured": false
  },
  {
    "id": "prod_007",
    "name": "Relaxed Fit Cargo Trousers",
    "description": "Durable cotton twill utility cargo pants with 6 pockets and adjustable ankle cuffs.",
    "price": 999,
    "originalPrice": 1699,
    "discount": 41,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 369,
    "stock": 15,
    "sku": "FA-007",
    "tags": [
      "cargos",
      "trousers",
      "streetwear",
      "utility"
    ],
    "featured": false
  },
  {
    "id": "prod_008",
    "name": "Cashmere Knit Turtleneck Sweater",
    "description": "Ultra-soft blended cashmere ribbed turtleneck sweater offering lightweight warmth.",
    "price": 1799,
    "originalPrice": 2799,
    "discount": 36,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 416,
    "stock": 9,
    "sku": "FA-008",
    "tags": [
      "sweater",
      "cashmere",
      "winter",
      "knitwear"
    ],
    "featured": true
  },
  {
    "id": "prod_009",
    "name": "Boho Tiered Maxi Dress",
    "description": "Flowy tiered maxi dress with ruffled hemlines and soft pastel tones.",
    "price": 1149,
    "originalPrice": 1899,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 83,
    "stock": 11,
    "sku": "FA-009",
    "tags": [
      "dress",
      "maxi",
      "boho",
      "summer"
    ],
    "featured": false
  },
  {
    "id": "prod_010",
    "name": "Tailored Single-Breasted Blazer",
    "description": "Structured modern-fit blazer with notch lapel, satin lining, and welt pockets.",
    "price": 2499,
    "originalPrice": 3999,
    "discount": 38,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 130,
    "stock": 7,
    "sku": "FA-010",
    "tags": [
      "blazer",
      "formal",
      "office",
      "outerwear"
    ],
    "featured": true
  },
  {
    "id": "prod_011",
    "name": "Embroidered Chikankari Kurta",
    "description": "Authentic handcrafted Lucknowi Chikankari modal kurta with intricate floral motifs.",
    "price": 849,
    "originalPrice": 1399,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 177,
    "stock": 17,
    "sku": "FA-011",
    "tags": [
      "chikankari",
      "kurta",
      "lucknowi",
      "traditional"
    ],
    "featured": false
  },
  {
    "id": "prod_012",
    "name": "High-Waist Wide Leg Jeans",
    "description": "Retro 90s aesthetic high-waisted wide-leg jeans in light vintage stone wash.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 224,
    "stock": 13,
    "sku": "FA-012",
    "tags": [
      "jeans",
      "denim",
      "wide-leg",
      "vintage"
    ],
    "featured": false
  },
  {
    "id": "prod_013",
    "name": "Fleece Lined Pullover Hoodie",
    "description": "Cozy brushed fleece hoodie with kangaroo pocket and double-layered drawstring hood.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 271,
    "stock": 22,
    "sku": "FA-013",
    "tags": [
      "hoodie",
      "fleece",
      "streetwear",
      "winter"
    ],
    "featured": false
  },
  {
    "id": "prod_014",
    "name": "Banarasi Brocade Silk Dupatta",
    "description": "Royal golden woven Banarasi silk dupatta to elevate any ethnic outfit.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 318,
    "stock": 18,
    "sku": "FA-014",
    "tags": [
      "dupatta",
      "banarasi",
      "brocade",
      "festive"
    ],
    "featured": false
  },
  {
    "id": "prod_015",
    "name": "Satin Silk Evening Slip Dress",
    "description": "Lustrous cowl-neck satin slip dress in emerald green with adjustable criss-cross straps.",
    "price": 1399,
    "originalPrice": 2299,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 365,
    "stock": 5,
    "sku": "FA-015",
    "tags": [
      "satin",
      "slip-dress",
      "partywear",
      "evening"
    ],
    "featured": true
  },
  {
    "id": "prod_016",
    "name": "Casual Cuban Collar Striped Shirt",
    "description": "Breezy resort-wear short sleeve shirt with retro vertical stripes and camp collar.",
    "price": 749,
    "originalPrice": 1199,
    "discount": 38,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80",
    "rating": 4,
    "reviewCount": 412,
    "stock": 14,
    "sku": "FA-016",
    "tags": [
      "shirt",
      "cuban-collar",
      "stripes",
      "resort"
    ],
    "featured": true
  },
  {
    "id": "prod_017",
    "name": "Quilted Puffer Winter Vest",
    "description": "Water-resistant lightweight thermal puffer gilet with stand collar and zip pockets.",
    "price": 1299,
    "originalPrice": 1999,
    "discount": 35,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 79,
    "stock": 8,
    "sku": "FA-017",
    "tags": [
      "vest",
      "puffer",
      "quilted",
      "winter"
    ],
    "featured": false
  },
  {
    "id": "prod_018",
    "name": "Pleated Velvet Party Skirt",
    "description": "Shimmering metallic velvet accordion pleat midi skirt with comfortable elastic waist.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 126,
    "stock": 10,
    "sku": "FA-018",
    "tags": [
      "skirt",
      "velvet",
      "pleated",
      "party"
    ],
    "featured": false
  },
  {
    "id": "prod_019",
    "name": "Cotton Linen Kurta Pajama Set",
    "description": "Classic mandarin collar men’s kurta in breathable cotton-linen paired with churidar.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 173,
    "stock": 12,
    "sku": "FA-019",
    "tags": [
      "kurta-set",
      "menswear",
      "ethnic",
      "linen"
    ],
    "featured": false
  },
  {
    "id": "prod_020",
    "name": "Cropped Teddy Bear Fleece Jacket",
    "description": "Super soft faux sherpa plush cropped jacket with zippered front and funnel neck.",
    "price": 1499,
    "originalPrice": 2399,
    "discount": 38,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 220,
    "stock": 7,
    "sku": "FA-020",
    "tags": [
      "jacket",
      "fleece",
      "teddy",
      "warm"
    ],
    "featured": false
  },
  {
    "id": "prod_021",
    "name": "Oxidized Silver Pearl Jhumkas",
    "description": "Traditional dome-shaped oxidized silver jhumkis accented with clustered mini pearls.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 267,
    "stock": 24,
    "sku": "JE-021",
    "tags": [
      "jhumka",
      "oxidized",
      "earrings",
      "silver"
    ],
    "featured": true
  },
  {
    "id": "prod_022",
    "name": "Kundan Choker Necklace Set",
    "description": "Exquisite handcrafted Jadau Kundan bridal choker with matching earrings and maang tikka.",
    "price": 999,
    "originalPrice": 1899,
    "discount": 47,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 314,
    "stock": 8,
    "sku": "JE-022",
    "tags": [
      "kundan",
      "necklace",
      "choker",
      "bridal"
    ],
    "featured": true
  },
  {
    "id": "prod_023",
    "name": "18K Gold Plated Evil Eye Bracelet",
    "description": "Delicate cubic zirconia evil eye charm bracelet finished in gleaming 18K yellow gold.",
    "price": 449,
    "originalPrice": 799,
    "discount": 44,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1611591475870-07e1591f4a9b?w=600&q=80",
    "rating": 4,
    "reviewCount": 361,
    "stock": 30,
    "sku": "JE-023",
    "tags": [
      "bracelet",
      "evil-eye",
      "gold-plated",
      "minimal"
    ],
    "featured": true
  },
  {
    "id": "prod_024",
    "name": "Vintage Bohemian Ring Stack (Set of 6)",
    "description": "Assorted carved antique silver-tone midi and knuckle rings with turquoise stone accents.",
    "price": 399,
    "originalPrice": 699,
    "discount": 43,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 408,
    "stock": 18,
    "sku": "JE-024",
    "tags": [
      "rings",
      "stackable",
      "boho",
      "vintage"
    ],
    "featured": true
  },
  {
    "id": "prod_025",
    "name": "Baroque Freshwater Pearl Pendant",
    "description": "Natural irregular baroque freshwater cultured pearl suspended on a dainty 14K gold chain.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
    "rating": 4,
    "reviewCount": 75,
    "stock": 15,
    "sku": "JE-025",
    "tags": [
      "pearl",
      "pendant",
      "necklace",
      "classic"
    ],
    "featured": false
  },
  {
    "id": "prod_026",
    "name": "Temple Art Lakshmi Coin Bangles",
    "description": "Intricately embossed matte antique gold Lakshmi kasu bangles (pair of 2).",
    "price": 799,
    "originalPrice": 1399,
    "discount": 43,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 122,
    "stock": 9,
    "sku": "JE-026",
    "tags": [
      "bangles",
      "temple",
      "lakshmi",
      "antique"
    ],
    "featured": false
  },
  {
    "id": "prod_027",
    "name": "Minimalist Chunky Huggie Hoops",
    "description": "Hypoallergenic stainless steel thick huggie hoop earrings with mirror polish.",
    "price": 299,
    "originalPrice": 499,
    "discount": 40,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 169,
    "stock": 26,
    "sku": "JE-027",
    "tags": [
      "hoops",
      "earrings",
      "minimal",
      "gold"
    ],
    "featured": false
  },
  {
    "id": "prod_028",
    "name": "Emerald Cut Solitaire Pendant",
    "description": "Radiant emerald-cut AAA grade cubic zirconia necklace prong-set in 925 sterling silver.",
    "price": 499,
    "originalPrice": 899,
    "discount": 44,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 216,
    "stock": 16,
    "sku": "JE-028",
    "tags": [
      "solitaire",
      "cz",
      "pendant",
      "silver"
    ],
    "featured": false
  },
  {
    "id": "prod_029",
    "name": "Rose Gold Floral Anklet Pair",
    "description": "Graceful twin chain rose-gold anklets with bell charms and sparkling crystal daisies.",
    "price": 379,
    "originalPrice": 599,
    "discount": 37,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 263,
    "stock": 20,
    "sku": "JE-029",
    "tags": [
      "anklet",
      "payal",
      "rose-gold",
      "floral"
    ],
    "featured": false
  },
  {
    "id": "prod_030",
    "name": "Meenakari Enamel Statement Ear Drops",
    "description": "Vibrant hand-painted Jaipur Meenakari lotus dangle earrings with seed bead fringe.",
    "price": 499,
    "originalPrice": 799,
    "discount": 38,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1590548784585-643d2b9f2925?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 310,
    "stock": 12,
    "sku": "JE-030",
    "tags": [
      "meenakari",
      "earrings",
      "handcrafted",
      "jaipur"
    ],
    "featured": false
  },
  {
    "id": "prod_031",
    "name": "Adjustable Sterling Silver Cuff Bangle",
    "description": "Hammered texture solid 925 hallmarked silver open cuff bangle suitable for daily wear.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1611591475870-07e1591f4a9b?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 357,
    "stock": 14,
    "sku": "JE-031",
    "tags": [
      "cuff",
      "bangle",
      "silver",
      "unisex"
    ],
    "featured": false
  },
  {
    "id": "prod_032",
    "name": "Geometric Crystal Statement Ring",
    "description": "Modernist hexagonal faceted zirconia cocktail ring mounted on a tapered band.",
    "price": 349,
    "originalPrice": 549,
    "discount": 36,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&q=80",
    "rating": 4,
    "reviewCount": 404,
    "stock": 17,
    "sku": "JE-032",
    "tags": [
      "ring",
      "crystal",
      "statement",
      "modern"
    ],
    "featured": true
  },
  {
    "id": "prod_033",
    "name": "Layered Paperclip Link Chain",
    "description": "Trendy dual-strand trombone paperclip link chain necklace with lobster clasp.",
    "price": 449,
    "originalPrice": 749,
    "discount": 40,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 71,
    "stock": 21,
    "sku": "JE-033",
    "tags": [
      "necklace",
      "paperclip",
      "chain",
      "layered"
    ],
    "featured": false
  },
  {
    "id": "prod_034",
    "name": "Tribal Afghan Mirror Choker",
    "description": "Authentic banjara tribal ghungroo neckpiece featuring reflective glass mirror work.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 118,
    "stock": 10,
    "sku": "JE-034",
    "tags": [
      "choker",
      "tribal",
      "mirror",
      "afghan"
    ],
    "featured": false
  },
  {
    "id": "prod_035",
    "name": "Opal Stone Constellation Studs",
    "description": "Ethereal iridescent synthetic fire opal studs in celestial north star settings.",
    "price": 329,
    "originalPrice": 599,
    "discount": 45,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 165,
    "stock": 28,
    "sku": "JE-035",
    "tags": [
      "studs",
      "opal",
      "celestial",
      "dainty"
    ],
    "featured": false
  },
  {
    "id": "prod_036",
    "name": "Cloudfoam Knit Running Sneakers",
    "description": "Ultra-responsive cushioning with breathable mesh knit upper and slip-resistant rubber outsole.",
    "price": 1299,
    "originalPrice": 2299,
    "discount": 43,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 212,
    "stock": 18,
    "sku": "FO-036",
    "tags": [
      "sneakers",
      "running",
      "cloudfoam",
      "athletics"
    ],
    "featured": true
  },
  {
    "id": "prod_037",
    "name": "Handcrafted Tan Penny Loafers",
    "description": "Supple vegan leather slip-on penny loafers with padded arch support and hand-stitched apron.",
    "price": 1899,
    "originalPrice": 3299,
    "discount": 42,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 259,
    "stock": 9,
    "sku": "FO-037",
    "tags": [
      "loafers",
      "leather",
      "formal",
      "tan"
    ],
    "featured": true
  },
  {
    "id": "prod_038",
    "name": "Chunky Sole Streetwear High-Tops",
    "description": "Bold ankle-support high-top court kicks with vulcanized platform soles and dual lace options.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 306,
    "stock": 11,
    "sku": "FO-038",
    "tags": [
      "sneakers",
      "high-top",
      "streetwear",
      "chunky"
    ],
    "featured": false
  },
  {
    "id": "prod_039",
    "name": "Strappy Block Heel Sandal",
    "description": "Comfortable 2.5-inch block heel dress sandals with ankle wrap buckles and cushioned footbed.",
    "price": 999,
    "originalPrice": 1699,
    "discount": 41,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 353,
    "stock": 14,
    "sku": "FO-039",
    "tags": [
      "heels",
      "sandals",
      "block-heel",
      "party"
    ],
    "featured": true
  },
  {
    "id": "prod_040",
    "name": "All-Terrain Chelsea Ankle Boots",
    "description": "Weatherproof matte finish pull-on Chelsea boots with elasticated side panels and rugged tread.",
    "price": 2199,
    "originalPrice": 3499,
    "discount": 37,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 400,
    "stock": 8,
    "sku": "FO-040",
    "tags": [
      "boots",
      "chelsea",
      "leather",
      "winter"
    ],
    "featured": true
  },
  {
    "id": "prod_041",
    "name": "Orthopedic Cushion Cloud Slides",
    "description": "Thick ergonomic EVA foam pillow slides offering instant relief for tired feet and indoor wear.",
    "price": 499,
    "originalPrice": 899,
    "discount": 44,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&q=80",
    "rating": 4,
    "reviewCount": 67,
    "stock": 35,
    "sku": "FO-041",
    "tags": [
      "slides",
      "comfort",
      "footwear",
      "waterproof"
    ],
    "featured": false
  },
  {
    "id": "prod_042",
    "name": "Classic Canvas Low-Top Plimsolls",
    "description": "Everyday durable 12oz cotton duck canvas lace-up shoes with contrast foxing stripe.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 114,
    "stock": 22,
    "sku": "FO-042",
    "tags": [
      "canvas",
      "sneakers",
      "casual",
      "skate"
    ],
    "featured": false
  },
  {
    "id": "prod_043",
    "name": "Pointed Toe Stiletto Court Shoes",
    "description": "Sophisticated 3.5-inch slim heel pumps in glossy patent nude finish with non-slip pads.",
    "price": 1399,
    "originalPrice": 2299,
    "discount": 39,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1581101767113-1677fc2beaa8?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 161,
    "stock": 7,
    "sku": "FO-043",
    "tags": [
      "heels",
      "stiletto",
      "court-shoes",
      "glamour"
    ],
    "featured": false
  },
  {
    "id": "prod_044",
    "name": "Braided Kolhapuri Leather Chappals",
    "description": "Handcrafted Kolhapur authentic toe-ring flats with t-strap braiding and pom-pom detailing.",
    "price": 649,
    "originalPrice": 999,
    "discount": 35,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 208,
    "stock": 16,
    "sku": "FO-044",
    "tags": [
      "kolhapuri",
      "ethnic",
      "chappal",
      "handmade"
    ],
    "featured": false
  },
  {
    "id": "prod_045",
    "name": "Trail Grip Hiking Trekking Shoes",
    "description": "Heavy-duty waterproof nubuck composite hiking shoes with shock-absorbing midsole.",
    "price": 1999,
    "originalPrice": 3199,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 255,
    "stock": 10,
    "sku": "FO-045",
    "tags": [
      "hiking",
      "boots",
      "outdoor",
      "trekking"
    ],
    "featured": false
  },
  {
    "id": "prod_046",
    "name": "Knit Slip-On Walking Espadrilles",
    "description": "Braided jute sole slip-on espadrilles with stretch breathable upper and flexible footbed.",
    "price": 799,
    "originalPrice": 1299,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 302,
    "stock": 19,
    "sku": "FO-046",
    "tags": [
      "espadrilles",
      "slip-on",
      "summer",
      "jute"
    ],
    "featured": false
  },
  {
    "id": "prod_047",
    "name": "Double Monk Strap Oxford Shoes",
    "description": "Burnished mahogany leather double monk strap shoes with gunmetal pin buckles.",
    "price": 2299,
    "originalPrice": 3699,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 349,
    "stock": 6,
    "sku": "FO-047",
    "tags": [
      "oxfords",
      "monk-strap",
      "leather",
      "luxury"
    ],
    "featured": false
  },
  {
    "id": "prod_048",
    "name": "Metallic Mule Flats with Bow",
    "description": "Chic backless mule flats with knotted bow upper and comfortable low stacked heel.",
    "price": 749,
    "originalPrice": 1199,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 396,
    "stock": 15,
    "sku": "FO-048",
    "tags": [
      "mules",
      "flats",
      "slip-on",
      "chic"
    ],
    "featured": true
  },
  {
    "id": "prod_049",
    "name": "Retro Gumsole Court Tennis Trainers",
    "description": "Vintage 80s inspired court sneakers with suede overlays and heritage gum rubber outsole.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 63,
    "stock": 20,
    "sku": "FO-049",
    "tags": [
      "trainers",
      "retro",
      "sneakers",
      "tennis"
    ],
    "featured": false
  },
  {
    "id": "prod_050",
    "name": "Velvet Embellished Wedding Mojaris",
    "description": "Traditional Punjabi juttis crafted in rich maroon velvet with zardozi thread embroidery.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 110,
    "stock": 13,
    "sku": "FO-050",
    "tags": [
      "mojari",
      "jutti",
      "ethnic",
      "wedding"
    ],
    "featured": false
  },
  {
    "id": "prod_051",
    "name": "Ultra Light SPF 50+ Sunscreen Gel",
    "description": "Invisible broad-spectrum SPF 50 PA++++ water gel sunscreen with zero white cast.",
    "price": 399,
    "originalPrice": 599,
    "discount": 33,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 157,
    "stock": 28,
    "sku": "BE-051",
    "tags": [
      "sunscreen",
      "skincare",
      "spf",
      "non-greasy"
    ],
    "featured": true
  },
  {
    "id": "prod_052",
    "name": "10% Niacinamide + Zinc Face Serum",
    "description": "Pore-refining lightweight serum that balances sebum production and fades dark spots.",
    "price": 449,
    "originalPrice": 699,
    "discount": 36,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 204,
    "stock": 32,
    "sku": "BE-052",
    "tags": [
      "serum",
      "niacinamide",
      "skincare",
      "blemish"
    ],
    "featured": true
  },
  {
    "id": "prod_053",
    "name": "Velvet Matte Liquid Lipstick Trio",
    "description": "12-hour smudge-proof transfer-resistant liquid lipsticks in 3 universally flattering nude tones.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 251,
    "stock": 25,
    "sku": "BE-053",
    "tags": [
      "lipstick",
      "matte",
      "makeup",
      "lip-color"
    ],
    "featured": true
  },
  {
    "id": "prod_054",
    "name": "Hyaluronic Acid Deep Moisture Cream",
    "description": "Triple molecular weight hyaluronic acid barrier moisturizer infused with ceramides.",
    "price": 499,
    "originalPrice": 799,
    "discount": 38,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 298,
    "stock": 20,
    "sku": "BE-054",
    "tags": [
      "moisturizer",
      "hyaluronic",
      "hydration",
      "barrier"
    ],
    "featured": false
  },
  {
    "id": "prod_055",
    "name": "Rosewater Glow Face Mist & Toner",
    "description": "Pure steam-distilled Kannauj damascena rosewater for instant dewy skin hydration.",
    "price": 299,
    "originalPrice": 499,
    "discount": 40,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1608248597359-545239a58406?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 345,
    "stock": 22,
    "sku": "BE-055",
    "tags": [
      "toner",
      "mist",
      "rosewater",
      "glow"
    ],
    "featured": false
  },
  {
    "id": "prod_056",
    "name": "Cold-Pressed Moroccan Argan Hair Oil",
    "description": "Rich golden organic argan elixir to tame frizz, mend split ends, and add salon-like shine.",
    "price": 649,
    "originalPrice": 999,
    "discount": 35,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 392,
    "stock": 17,
    "sku": "BE-056",
    "tags": [
      "haircare",
      "argan-oil",
      "hair-serum",
      "frizz"
    ],
    "featured": true
  },
  {
    "id": "prod_057",
    "name": "Vitamin C Brightening Daily Cleanser",
    "description": "Gentle foaming face wash infused with Kakadu plum vitamin C to revive tired dull skin.",
    "price": 349,
    "originalPrice": 549,
    "discount": 36,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 59,
    "stock": 30,
    "sku": "BE-057",
    "tags": [
      "facewash",
      "vitamin-c",
      "cleanser",
      "brightening"
    ],
    "featured": false
  },
  {
    "id": "prod_058",
    "name": "Volumizing Waterproof Kohl Kajal",
    "description": "Intense 24-hour jet black matte eyeliner pencil enriched with soothing almond oil.",
    "price": 249,
    "originalPrice": 399,
    "discount": 38,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 106,
    "stock": 40,
    "sku": "BE-058",
    "tags": [
      "kajal",
      "eyeliner",
      "smudgeproof",
      "kohl"
    ],
    "featured": false
  },
  {
    "id": "prod_059",
    "name": "French Vanilla Whipped Body Butter",
    "description": "Velvety whipped raw shea and cocoa butter with an intoxicating warm bourbon vanilla aroma.",
    "price": 479,
    "originalPrice": 799,
    "discount": 40,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1567928815116-f6d34b4c7308?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 153,
    "stock": 15,
    "sku": "BE-059",
    "tags": [
      "body-butter",
      "vanilla",
      "shea",
      "bodycare"
    ],
    "featured": false
  },
  {
    "id": "prod_060",
    "name": "Oud & Bergamot Luxury Eau De Parfum (50ml)",
    "description": "Long-lasting intoxicating artisanal blend of smoky agarwood, sparkling citrus, and cedar.",
    "price": 1299,
    "originalPrice": 2199,
    "discount": 41,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80",
    "rating": 4,
    "reviewCount": 200,
    "stock": 12,
    "sku": "BE-060",
    "tags": [
      "perfume",
      "fragrance",
      "oud",
      "luxury"
    ],
    "featured": true
  },
  {
    "id": "prod_061",
    "name": "Green Tea & Salicylic Detox Clay Mask",
    "description": "Mineral French green clay mask with 2% BHA to decongest pores without stripping moisture.",
    "price": 429,
    "originalPrice": 699,
    "discount": 39,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 247,
    "stock": 18,
    "sku": "BE-061",
    "tags": [
      "clay-mask",
      "detox",
      "acne",
      "greentea"
    ],
    "featured": false
  },
  {
    "id": "prod_062",
    "name": "Tinted Peptide Lip Therapy Plumper",
    "description": "High-shine nourishing peptide lip butter delivering instant volume and juicy berry tint.",
    "price": 379,
    "originalPrice": 599,
    "discount": 37,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1599733589046-10c005739ef9?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 294,
    "stock": 26,
    "sku": "BE-062",
    "tags": [
      "lip-balm",
      "peptides",
      "gloss",
      "plumping"
    ],
    "featured": false
  },
  {
    "id": "prod_063",
    "name": "Rose Quartz Gua Sha & Facial Roller Set",
    "description": "100% natural grade A rose quartz face sculptor to contour jawlines and boost lymphatic drainage.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1590156221185-c5215233d650?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 341,
    "stock": 14,
    "sku": "BE-063",
    "tags": [
      "gua-sha",
      "skincare-tool",
      "facial",
      "rosequartz"
    ],
    "featured": false
  },
  {
    "id": "prod_064",
    "name": "Keratin Damage Repair Hair Mask",
    "description": "Intense reconstructive protein mask to repair chemically damaged, bleached, or heat-styled hair.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 388,
    "stock": 16,
    "sku": "BE-064",
    "tags": [
      "hair-mask",
      "keratin",
      "repair",
      "haircare"
    ],
    "featured": true
  },
  {
    "id": "prod_065",
    "name": "Gentle Micellar Bi-Phase Makeup Remover",
    "description": "Lifts waterproof mascara and stubborn makeup effortlessly with no tugging or greasy residue.",
    "price": 299,
    "originalPrice": 499,
    "discount": 40,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 55,
    "stock": 24,
    "sku": "BE-065",
    "tags": [
      "makeup-remover",
      "micellar",
      "skincare",
      "cleanse"
    ],
    "featured": false
  },
  {
    "id": "prod_066",
    "name": "Classic Aviator Polarized Sunglasses",
    "description": "Full UV400 polarized teardrop aviators in gunmetal alloy frame with scratch-resistant lenses.",
    "price": 799,
    "originalPrice": 1499,
    "discount": 47,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 102,
    "stock": 20,
    "sku": "AC-066",
    "tags": [
      "sunglasses",
      "polarized",
      "aviator",
      "eyewear"
    ],
    "featured": true
  },
  {
    "id": "prod_067",
    "name": "Genuine Full-Grain Leather Wallet",
    "description": "Slim bifold vintage pull-up leather wallet equipped with RFID blocking security lining.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    "rating": 4,
    "reviewCount": 149,
    "stock": 24,
    "sku": "AC-067",
    "tags": [
      "wallet",
      "leather",
      "rfid",
      "accessories"
    ],
    "featured": true
  },
  {
    "id": "prod_068",
    "name": "Minimalist Minimal Bauhaus Analog Watch",
    "description": "Clean 40mm stainless steel case with Japanese quartz movement and genuine mesh strap.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 196,
    "stock": 11,
    "sku": "AC-068",
    "tags": [
      "watch",
      "analog",
      "minimalist",
      "accessories"
    ],
    "featured": true
  },
  {
    "id": "prod_069",
    "name": "Structured Vegan Leather Tote Handbag",
    "description": "Spacious work-to-weekend shoulder tote with zippered laptop compartment and gold hardware.",
    "price": 1299,
    "originalPrice": 2199,
    "discount": 41,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80",
    "rating": 4,
    "reviewCount": 243,
    "stock": 13,
    "sku": "AC-069",
    "tags": [
      "handbag",
      "tote",
      "vegan-leather",
      "bag"
    ],
    "featured": false
  },
  {
    "id": "prod_070",
    "name": "Reversible Italian Leather Formal Belt",
    "description": "Dual-tone black and cognac brown 35mm dress belt with twist-lock brushed steel buckle.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 290,
    "stock": 19,
    "sku": "AC-070",
    "tags": [
      "belt",
      "leather",
      "reversible",
      "formal"
    ],
    "featured": false
  },
  {
    "id": "prod_071",
    "name": "Pashmina Cashmere Silk Blend Scarf",
    "description": "Feather-light warm woven shawl with delicate eyelash fringe and jacquard paisley border.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 337,
    "stock": 16,
    "sku": "AC-071",
    "tags": [
      "scarf",
      "pashmina",
      "cashmere",
      "winter"
    ],
    "featured": false
  },
  {
    "id": "prod_072",
    "name": "Water-Repellent Commuter Laptop Backpack",
    "description": "25L anti-theft tech backpack with 15.6 inch padded sleeve, USB port, and luggage strap.",
    "price": 1599,
    "originalPrice": 2699,
    "discount": 41,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 384,
    "stock": 15,
    "sku": "AC-072",
    "tags": [
      "backpack",
      "laptop-bag",
      "commute",
      "travel"
    ],
    "featured": true
  },
  {
    "id": "prod_073",
    "name": "Chunky Knit Beanie Cap",
    "description": "Thermal ribbed acrylic watch cap with turn-up cuff for cozy autumn and winter warmth.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 51,
    "stock": 30,
    "sku": "AC-073",
    "tags": [
      "beanie",
      "winter",
      "knit",
      "cap"
    ],
    "featured": false
  },
  {
    "id": "prod_074",
    "name": "Vintage Retro Cat-Eye Sunglasses",
    "description": "Chic tortoiseshell acetate cat-eye shades with 100% UV protection and gradient tint.",
    "price": 649,
    "originalPrice": 1099,
    "discount": 41,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 98,
    "stock": 18,
    "sku": "AC-074",
    "tags": [
      "sunglasses",
      "cateye",
      "retro",
      "eyewear"
    ],
    "featured": false
  },
  {
    "id": "prod_075",
    "name": "Compact Key Organizer & EDC Pocket Clip",
    "description": "Aircraft-grade anodized aluminum silent key holder holding up to 8 keys cleanly.",
    "price": 399,
    "originalPrice": 699,
    "discount": 43,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 145,
    "stock": 25,
    "sku": "AC-075",
    "tags": [
      "keychain",
      "edc",
      "organizer",
      "minimal"
    ],
    "featured": false
  },
  {
    "id": "prod_076",
    "name": "Canvas Crossbody Sling Bag",
    "description": "Hands-free compact chest sling with adjustable strap, earphone port, and security pocket.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    "rating": 4,
    "reviewCount": 192,
    "stock": 17,
    "sku": "AC-076",
    "tags": [
      "sling-bag",
      "crossbody",
      "canvas",
      "travel"
    ],
    "featured": false
  },
  {
    "id": "prod_077",
    "name": "Classic Silk Pocket Square (Set of 3)",
    "description": "Hand-rolled pure mulberry silk pocket squares in floral, polka dot, and solid shades.",
    "price": 449,
    "originalPrice": 799,
    "discount": 44,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 239,
    "stock": 20,
    "sku": "AC-077",
    "tags": [
      "pocket-square",
      "silk",
      "formal",
      "accessories"
    ],
    "featured": false
  },
  {
    "id": "prod_078",
    "name": "Automatic Travel Compact Umbrella",
    "description": "One-touch auto open/close 10-rib wind-defying teflon coated umbrella with slip cover.",
    "price": 499,
    "originalPrice": 849,
    "discount": 41,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 286,
    "stock": 22,
    "sku": "AC-078",
    "tags": [
      "umbrella",
      "travel",
      "rain",
      "windproof"
    ],
    "featured": false
  },
  {
    "id": "prod_079",
    "name": "Active Noise Cancelling True Wireless Earbuds",
    "description": "Bluetooth 5.3 earbuds featuring 35dB hybrid ANC, low-latency gaming mode, and 36hr battery.",
    "price": 1899,
    "originalPrice": 3499,
    "discount": 46,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 333,
    "stock": 16,
    "sku": "EL-079",
    "tags": [
      "earbuds",
      "anc",
      "wireless",
      "audio"
    ],
    "featured": true
  },
  {
    "id": "prod_080",
    "name": "1.43” AMOLED Smartwatch with Bluetooth Calling",
    "description": "Always-on crisp AMOLED display with heart rate, SpO2 sensor, 100+ sports modes, and zinc casing.",
    "price": 2199,
    "originalPrice": 3999,
    "discount": 45,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 380,
    "stock": 14,
    "sku": "EL-080",
    "tags": [
      "smartwatch",
      "fitness",
      "amoled",
      "wearable"
    ],
    "featured": true
  },
  {
    "id": "prod_081",
    "name": "Compact 68-Key Hot-Swap Mechanical Keyboard",
    "description": "RGB backlit mechanical typing keyboard with pre-lubed linear red switches and detachable USB-C.",
    "price": 2499,
    "originalPrice": 4299,
    "discount": 42,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 47,
    "stock": 10,
    "sku": "EL-081",
    "tags": [
      "keyboard",
      "mechanical",
      "rgb",
      "gaming"
    ],
    "featured": true
  },
  {
    "id": "prod_082",
    "name": "Portable 360° Waterproof Bluetooth Speaker",
    "description": "IPX7 floating rugged outdoor sound cylinder with punchy passive bass radiators and 14h playtime.",
    "price": 1199,
    "originalPrice": 1999,
    "discount": 40,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 94,
    "stock": 20,
    "sku": "EL-082",
    "tags": [
      "speaker",
      "bluetooth",
      "waterproof",
      "audio"
    ],
    "featured": false
  },
  {
    "id": "prod_083",
    "name": "65W GaN Fast Charger with 3 Ports",
    "description": "Pocket-sized gallium nitride power adapter fast charging laptops, tablets, and phones simultaneously.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 141,
    "stock": 28,
    "sku": "EL-083",
    "tags": [
      "charger",
      "gan",
      "usbc",
      "fast-charging"
    ],
    "featured": false
  },
  {
    "id": "prod_084",
    "name": "MagSafe Compatible 10,000mAh Power Bank",
    "description": "Strong magnetic snap-on wireless portable charger with foldable kickstand and digital LED % display.",
    "price": 1399,
    "originalPrice": 2299,
    "discount": 39,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1609592424300-d26b527848f2?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 188,
    "stock": 18,
    "sku": "EL-084",
    "tags": [
      "powerbank",
      "magsafe",
      "wireless",
      "battery"
    ],
    "featured": false
  },
  {
    "id": "prod_085",
    "name": "Studio Monitoring Over-Ear Headphones",
    "description": "Precision-tuned 50mm neodymium drivers for crystalline highs, rich mids, and memory-foam pads.",
    "price": 2799,
    "originalPrice": 4499,
    "discount": 38,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 235,
    "stock": 8,
    "sku": "EL-085",
    "tags": [
      "headphones",
      "over-ear",
      "audiophile",
      "studio"
    ],
    "featured": true
  },
  {
    "id": "prod_086",
    "name": "Ergonomic Vertical Wireless Mouse",
    "description": "Natural handshake 57° vertical posture mouse reducing wrist strain with silent click buttons.",
    "price": 799,
    "originalPrice": 1399,
    "discount": 43,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 282,
    "stock": 22,
    "sku": "EL-086",
    "tags": [
      "mouse",
      "ergonomic",
      "office",
      "wireless"
    ],
    "featured": false
  },
  {
    "id": "prod_087",
    "name": "Full HD USB Streaming Webcam with Privacy Cover",
    "description": "1080p 60FPS autofocus wide-angle video conference camera with dual noise-cancelling mics.",
    "price": 1099,
    "originalPrice": 1899,
    "discount": 42,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 329,
    "stock": 15,
    "sku": "EL-087",
    "tags": [
      "webcam",
      "streaming",
      "workfromhome",
      "video"
    ],
    "featured": false
  },
  {
    "id": "prod_088",
    "name": "Smart LED Light Bar for Monitors",
    "description": "Asymmetric anti-glare screen hanging light bar with touch controls and adjustable color temperature.",
    "price": 999,
    "originalPrice": 1699,
    "discount": 41,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
    "rating": 4.5,
    "reviewCount": 376,
    "stock": 17,
    "sku": "EL-088",
    "tags": [
      "screenbar",
      "desk-setup",
      "lighting",
      "productivity"
    ],
    "featured": true
  },
  {
    "id": "prod_089",
    "name": "3-in-1 Foldable Wireless Charging Station",
    "description": "Sleek travel charging stand for iPhone, Apple Watch, and AirPods at the same time.",
    "price": 1299,
    "originalPrice": 2099,
    "discount": 38,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 43,
    "stock": 14,
    "sku": "EL-089",
    "tags": [
      "charger",
      "wireless",
      "dock",
      "apple"
    ],
    "featured": false
  },
  {
    "id": "prod_090",
    "name": "Universal Travel Adapter with PD 30W",
    "description": "Worldwide all-in-one plug adapter compatible with EU, US, UK, AU and 150+ countries.",
    "price": 649,
    "originalPrice": 1099,
    "discount": 41,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 90,
    "stock": 25,
    "sku": "EL-090",
    "tags": [
      "travel-adapter",
      "plug",
      "universal",
      "travel"
    ],
    "featured": false
  },
  {
    "id": "prod_091",
    "name": "Aromatherapy Soy Wax Scented Candle",
    "description": "Clean burning 100% natural soy wax infused with French lavender and sweet vanilla bean.",
    "price": 449,
    "originalPrice": 799,
    "discount": 44,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 137,
    "stock": 25,
    "sku": "HO-091",
    "tags": [
      "candle",
      "aromatherapy",
      "homedecor",
      "relax"
    ],
    "featured": true
  },
  {
    "id": "prod_092",
    "name": "Handmade Matte Ceramic Coffee Mug",
    "description": "Studio handcrafted speckled stoneware pottery mug with ergonomic comfortable handle (350ml).",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80",
    "rating": 4.4,
    "reviewCount": 184,
    "stock": 30,
    "sku": "HO-092",
    "tags": [
      "mug",
      "ceramic",
      "coffee",
      "kitchen"
    ],
    "featured": false
  },
  {
    "id": "prod_093",
    "name": "Minimalist Nordic Wooden Desk Lamp",
    "description": "Scandinavian solid beech wood articulated arm table lamp with warm white LED bulb.",
    "price": 1299,
    "originalPrice": 2199,
    "discount": 41,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 231,
    "stock": 12,
    "sku": "HO-093",
    "tags": [
      "lamp",
      "lighting",
      "desk",
      "nordic"
    ],
    "featured": true
  },
  {
    "id": "prod_094",
    "name": "Boho Tufted Geometric Cushion Cover",
    "description": "Textured woven heavy cotton canvas throw pillow cover with tufting and corner tassels.",
    "price": 399,
    "originalPrice": 699,
    "discount": 43,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=80",
    "rating": 3.9,
    "reviewCount": 278,
    "stock": 22,
    "sku": "HO-094",
    "tags": [
      "cushion",
      "pillow",
      "boho",
      "livingroom"
    ],
    "featured": false
  },
  {
    "id": "prod_095",
    "name": "Indoor Ceramic Planter with Wooden Stand",
    "description": "White fluted cylinder ceramic plant pot paired with natural cross-braced acacia wood stand.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=80",
    "rating": 4,
    "reviewCount": 325,
    "stock": 15,
    "sku": "HO-095",
    "tags": [
      "planter",
      "plants",
      "ceramic",
      "decor"
    ],
    "featured": false
  },
  {
    "id": "prod_096",
    "name": "Ultrasonic Woodgrain Essential Oil Diffuser",
    "description": "Whisper-quiet 400ml ultrasonic cool mist humidifier with 7 soothing ambient LED lights.",
    "price": 899,
    "originalPrice": 1499,
    "discount": 40,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 372,
    "stock": 18,
    "sku": "HO-096",
    "tags": [
      "diffuser",
      "aromatherapy",
      "humidifier",
      "wellness"
    ],
    "featured": true
  },
  {
    "id": "prod_097",
    "name": "Double-Walled Insulated French Press (800ml)",
    "description": "Mirror-polished 304 food-grade stainless steel cafetiere that keeps coffee hot for 2 hours.",
    "price": 1199,
    "originalPrice": 1899,
    "discount": 37,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1517668808822-9ebd02f2a8ea?w=600&q=80",
    "rating": 4.6,
    "reviewCount": 419,
    "stock": 14,
    "sku": "HO-097",
    "tags": [
      "french-press",
      "coffee",
      "kitchen",
      "stainless"
    ],
    "featured": true
  },
  {
    "id": "prod_098",
    "name": "Bamboo Bathtub Caddy Tray",
    "description": "Expandable waterproof organic bamboo bath bridge with book holder, wine glass slot, and phone rest.",
    "price": 999,
    "originalPrice": 1699,
    "discount": 41,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 86,
    "stock": 10,
    "sku": "HO-098",
    "tags": [
      "bath",
      "bamboo",
      "tray",
      "spa"
    ],
    "featured": false
  },
  {
    "id": "prod_099",
    "name": "Textured Waffle Cotton Bath Towel",
    "description": "Quick-drying honeycomb weave 100% Turkish cotton large bath sheet in slate grey.",
    "price": 499,
    "originalPrice": 899,
    "discount": 44,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 133,
    "stock": 26,
    "sku": "HO-099",
    "tags": [
      "towel",
      "cotton",
      "waffle",
      "bath"
    ],
    "featured": false
  },
  {
    "id": "prod_100",
    "name": "Abstract Minimalist Botanical Wall Art (Framed)",
    "description": "High-definition giclée print on textured linen paper housed in a natural oak composite frame.",
    "price": 799,
    "originalPrice": 1399,
    "discount": 43,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 180,
    "stock": 16,
    "sku": "HO-100",
    "tags": [
      "wall-art",
      "decor",
      "framed",
      "prints"
    ],
    "featured": false
  },
  {
    "id": "prod_101",
    "name": "Pure Brass Incense Burner & Dhoop Stand",
    "description": "Handcrafted solid golden brass agarbatti holder with ash-catcher tray for daily puja and zen.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 227,
    "stock": 28,
    "sku": "HO-101",
    "tags": [
      "incense",
      "brass",
      "spiritual",
      "home"
    ],
    "featured": false
  },
  {
    "id": "prod_102",
    "name": "Modern Minimalist Wall Clock (12-inch)",
    "description": "Non-ticking silent sweep quartz wall clock with clean matte numerals and glass cover.",
    "price": 749,
    "originalPrice": 1299,
    "discount": 42,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600&q=80",
    "rating": 4,
    "reviewCount": 274,
    "stock": 17,
    "sku": "HO-102",
    "tags": [
      "clock",
      "wall-clock",
      "silent",
      "minimal"
    ],
    "featured": false
  },
  {
    "id": "prod_103",
    "name": "Block Printed Cotton Mulmul Saree",
    "description": "Bagru hand-block printed lightweight mulmul cotton saree for daily office elegance.",
    "price": 999,
    "originalPrice": 1599,
    "discount": 38,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 372,
    "stock": 12,
    "sku": "FA-103",
    "tags": [
      "saree",
      "mulmul",
      "cotton",
      "blockprint"
    ],
    "featured": false
  },
  {
    "id": "prod_104",
    "name": "Oversized Flannel Plaid Shirt",
    "description": "Heavyweight brushed cotton plaid flannel shirt with twin button flap pockets.",
    "price": 849,
    "originalPrice": 1399,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 411,
    "stock": 18,
    "sku": "FA-104",
    "tags": [
      "shirt",
      "flannel",
      "plaid",
      "casual"
    ],
    "featured": false
  },
  {
    "id": "prod_105",
    "name": "Khadi Cotton Short Kurta",
    "description": "Eco-friendly breathable handspun khadi short tunic shirt in earthy beige.",
    "price": 599,
    "originalPrice": 999,
    "discount": 40,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 450,
    "stock": 22,
    "sku": "FA-105",
    "tags": [
      "kurta",
      "khadi",
      "menswear",
      "casual"
    ],
    "featured": false
  },
  {
    "id": "prod_106",
    "name": "Silk Jacquard Festive Kurta Set",
    "description": "Lustrous self-woven silk blend kurta with contrast pyjama and churidar.",
    "price": 1699,
    "originalPrice": 2799,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 79,
    "stock": 7,
    "sku": "FA-106",
    "tags": [
      "kurta",
      "festive",
      "silk",
      "ethnic"
    ],
    "featured": false
  },
  {
    "id": "prod_107",
    "name": "Faux Leather Biker Motorcycle Jacket",
    "description": "Asymmetrical zip moto jacket with notched lapel and zippered cuff hardware.",
    "price": 2199,
    "originalPrice": 3599,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 118,
    "stock": 6,
    "sku": "FA-107",
    "tags": [
      "leather-jacket",
      "biker",
      "outerwear",
      "black"
    ],
    "featured": false
  },
  {
    "id": "prod_108",
    "name": "Tiered Linen Midi Sun Dress",
    "description": "Sun-drenched buttercup yellow linen dress with shirred back and puff sleeves.",
    "price": 1049,
    "originalPrice": 1699,
    "discount": 38,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 157,
    "stock": 15,
    "sku": "FA-108",
    "tags": [
      "dress",
      "midi",
      "linen",
      "summer"
    ],
    "featured": true
  },
  {
    "id": "prod_109",
    "name": "Washed Denim Dungaree Overalls",
    "description": "Relaxed fit classic utility denim overalls with adjustable buckle bib straps.",
    "price": 1349,
    "originalPrice": 2199,
    "discount": 39,
    "category": "Fashion",
    "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 196,
    "stock": 10,
    "sku": "FA-109",
    "tags": [
      "dungarees",
      "overalls",
      "denim",
      "casual"
    ],
    "featured": false
  },
  {
    "id": "prod_110",
    "name": "Kashmiri Jhumka with Hair Chain",
    "description": "Traditional Kashmiri hanging sahara ear chains connecting to pearl-fringed bell drops.",
    "price": 499,
    "originalPrice": 899,
    "discount": 44,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 235,
    "stock": 14,
    "sku": "JE-110",
    "tags": [
      "jhumka",
      "kashmiri",
      "hair-chain",
      "bridal"
    ],
    "featured": false
  },
  {
    "id": "prod_111",
    "name": "Beaded Multi-Layer Choker Set",
    "description": "Turquoise and terracotta glass seed bead necklace stack with adjustable tie.",
    "price": 379,
    "originalPrice": 649,
    "discount": 42,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600&q=80",
    "rating": 4.9,
    "reviewCount": 274,
    "stock": 20,
    "sku": "JE-111",
    "tags": [
      "choker",
      "beaded",
      "boho",
      "layers"
    ],
    "featured": false
  },
  {
    "id": "prod_112",
    "name": "Swarovski Zirconia Nose Pin (Clip-On)",
    "description": "No-piercing required sparkling floral clip-on nose stud in gold-plated brass.",
    "price": 249,
    "originalPrice": 449,
    "discount": 45,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 313,
    "stock": 35,
    "sku": "JE-112",
    "tags": [
      "nose-pin",
      "clip-on",
      "cz",
      "ethnic"
    ],
    "featured": false
  },
  {
    "id": "prod_113",
    "name": "Antique Oxidized Waist Belt (Kamarbandh)",
    "description": "Sculpted ghungroo hanging waist chain to accent sarees and lehengas.",
    "price": 699,
    "originalPrice": 1299,
    "discount": 46,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    "rating": 4.1,
    "reviewCount": 352,
    "stock": 8,
    "sku": "JE-113",
    "tags": [
      "kamarbandh",
      "waist-belt",
      "oxidized",
      "belly-chain"
    ],
    "featured": false
  },
  {
    "id": "prod_114",
    "name": "Enamel Daisy Flower Stud Earrings",
    "description": "Cute pastel yellow and white enamel daisy button studs with push-back pin.",
    "price": 289,
    "originalPrice": 499,
    "discount": 42,
    "category": "Jewellery",
    "image": "https://images.unsplash.com/photo-1590548784585-643d2b9f2925?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 391,
    "stock": 25,
    "sku": "JE-114",
    "tags": [
      "studs",
      "daisy",
      "floral",
      "cute"
    ],
    "featured": true
  },
  {
    "id": "prod_115",
    "name": "Breathable Slip-On Mesh Loafers",
    "description": "Ultra lightweight air-mesh slip-ons designed for high mileage and hot days.",
    "price": 799,
    "originalPrice": 1299,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 430,
    "stock": 22,
    "sku": "FO-115",
    "tags": [
      "loafers",
      "mesh",
      "walking",
      "comfort"
    ],
    "featured": false
  },
  {
    "id": "prod_116",
    "name": "Ankle Strap Espadrille Wedges",
    "description": "Jute wrapped 3-inch wedge heel sandals with soft microfiber suede upper.",
    "price": 1199,
    "originalPrice": 1899,
    "discount": 37,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 59,
    "stock": 12,
    "sku": "FO-116",
    "tags": [
      "wedges",
      "espadrilles",
      "summer",
      "heels"
    ],
    "featured": false
  },
  {
    "id": "prod_117",
    "name": "Reflective Night Runner Road Shoes",
    "description": "High-visibility 3M reflective road trainers with carbon-reinforced torsion plate.",
    "price": 1699,
    "originalPrice": 2799,
    "discount": 39,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 98,
    "stock": 14,
    "sku": "FO-117",
    "tags": [
      "running",
      "reflective",
      "marathon",
      "sport"
    ],
    "featured": false
  },
  {
    "id": "prod_118",
    "name": "Classic Derby Brogue Formal Shoes",
    "description": "Wingtip perforated derby dress shoes in rich burnished chestnut brown.",
    "price": 2099,
    "originalPrice": 3399,
    "discount": 38,
    "category": "Footwear",
    "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 137,
    "stock": 8,
    "sku": "FO-118",
    "tags": [
      "brogues",
      "derby",
      "leather",
      "formal"
    ],
    "featured": false
  },
  {
    "id": "prod_119",
    "name": "Avocado Cold Pressed Nourishing Night Oil",
    "description": "Deeply restoring night face oil rich in vitamins A, D, and E for supple glowing skin.",
    "price": 549,
    "originalPrice": 899,
    "discount": 39,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 176,
    "stock": 17,
    "sku": "BE-119",
    "tags": [
      "face-oil",
      "avocado",
      "nightcare",
      "skincare"
    ],
    "featured": false
  },
  {
    "id": "prod_120",
    "name": "Mineral Rice Water Clarifying Shampoo",
    "description": "Sulfate-free fermented rice water shampoo that prevents hair fall and adds gloss.",
    "price": 399,
    "originalPrice": 599,
    "discount": 33,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 215,
    "stock": 26,
    "sku": "BE-120",
    "tags": [
      "shampoo",
      "ricewater",
      "haircare",
      "sulfate-free"
    ],
    "featured": true
  },
  {
    "id": "prod_121",
    "name": "Exfoliating Walnut & Apricot Face Scrub",
    "description": "Micro-fine walnut beads and cold-pressed apricot kernel oil to buff away dead cells.",
    "price": 299,
    "originalPrice": 449,
    "discount": 33,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 254,
    "stock": 21,
    "sku": "BE-121",
    "tags": [
      "scrub",
      "exfoliate",
      "walnut",
      "cleanse"
    ],
    "featured": false
  },
  {
    "id": "prod_122",
    "name": "24K Gold Foil Revitalizing Eye Patches (30 Pairs)",
    "description": "Hydrogel collagen cooling eye patches that soothe morning puffiness and under-eye circles.",
    "price": 499,
    "originalPrice": 849,
    "discount": 41,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 293,
    "stock": 19,
    "sku": "BE-122",
    "tags": [
      "eye-mask",
      "hydrogel",
      "gold",
      "anti-fatigue"
    ],
    "featured": false
  },
  {
    "id": "prod_123",
    "name": "Minimalist Titanium Key Carabiner",
    "description": "Sturdy ultra-light aerospace grade titanium keychain clip with integrated bottle opener.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 332,
    "stock": 30,
    "sku": "AC-123",
    "tags": [
      "carabiner",
      "titanium",
      "edc",
      "keys"
    ],
    "featured": false
  },
  {
    "id": "prod_124",
    "name": "Silk Twill Hair Scrunchies (Pack of 5)",
    "description": "100% pure Mulberry silk scrunchies that eliminate creases, tugging, and hair breakage.",
    "price": 299,
    "originalPrice": 499,
    "discount": 40,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 371,
    "stock": 45,
    "sku": "AC-124",
    "tags": [
      "scrunchie",
      "silk",
      "hair",
      "accessories"
    ],
    "featured": false
  },
  {
    "id": "prod_125",
    "name": "Retro Hexagonal Metal Frame Glasses",
    "description": "Slim gold wireframe geometric reading and blue-light computer glasses.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 410,
    "stock": 18,
    "sku": "AC-125",
    "tags": [
      "glasses",
      "spectacles",
      "hexagonal",
      "vintage"
    ],
    "featured": false
  },
  {
    "id": "prod_126",
    "name": "Adjustable Aluminum Laptop Riser Stand",
    "description": "Foldable ventilated desktop elevation mount supporting all 10-17 inch laptops.",
    "price": 699,
    "originalPrice": 1199,
    "discount": 42,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 449,
    "stock": 24,
    "sku": "EL-126",
    "tags": [
      "laptop-stand",
      "aluminum",
      "desk",
      "ergonomic"
    ],
    "featured": true
  },
  {
    "id": "prod_127",
    "name": "Braided 100W USB-C to USB-C Cable (2m)",
    "description": "Nylon armored heavy-duty cable with E-marker chip supporting 100W PD charging.",
    "price": 349,
    "originalPrice": 599,
    "discount": 42,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 78,
    "stock": 50,
    "sku": "EL-127",
    "tags": [
      "cable",
      "usbc",
      "100w",
      "fastcharge"
    ],
    "featured": false
  },
  {
    "id": "prod_128",
    "name": "RGB Gaming Mousepad with Wireless Charging",
    "description": "800x300mm extended micro-textured surface with 15W fast phone charging zone.",
    "price": 999,
    "originalPrice": 1699,
    "discount": 41,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
    "rating": 4.7,
    "reviewCount": 117,
    "stock": 15,
    "sku": "EL-128",
    "tags": [
      "mousepad",
      "rgb",
      "wireless-charging",
      "gaming"
    ],
    "featured": false
  },
  {
    "id": "prod_129",
    "name": "Handwoven Natural Jute Floor Rug (4x6 ft)",
    "description": "Organic eco-friendly braided golden jute area rug adding rustic bohemian charm.",
    "price": 1499,
    "originalPrice": 2499,
    "discount": 40,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600&q=80",
    "rating": 4.2,
    "reviewCount": 156,
    "stock": 8,
    "sku": "HO-129",
    "tags": [
      "rug",
      "jute",
      "boho",
      "homedecor"
    ],
    "featured": false
  },
  {
    "id": "prod_130",
    "name": "Borosilicate Glass Water Bottle with Bamboo Lid",
    "description": "Eco-conscious thermal-shock proof 750ml glass drinkware with silicone protective sleeve.",
    "price": 449,
    "originalPrice": 799,
    "discount": 44,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1517668808822-9ebd02f2a8ea?w=600&q=80",
    "rating": 4.3,
    "reviewCount": 195,
    "stock": 28,
    "sku": "HO-130",
    "tags": [
      "bottle",
      "glass",
      "bamboo",
      "sustainable"
    ],
    "featured": false
  },
  {
    "id": "prod_131",
    "name": "Set of 4 Marble & Acacia Wood Coasters",
    "description": "Geometric split white marble and natural acacia beverage coasters with felt base pads.",
    "price": 399,
    "originalPrice": 699,
    "discount": 43,
    "category": "Home & Living",
    "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80",
    "rating": 4.8,
    "reviewCount": 234,
    "stock": 22,
    "sku": "HO-131",
    "tags": [
      "coasters",
      "marble",
      "wood",
      "dining"
    ],
    "featured": false
  }
];
